#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#BRANCH=$(git rev-parse --abbrev-ref HEAD)
#PROTECTED_BRANCHES="^(master|develop)"

## shellcheck disable=SC2039
#if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
#then
#  echo -e "\n🚫 [commit-msg] Cannot commit on $BRANCH branch, please create your own branch" && exit 1
#fi

pnpx commitlint --edit "$1"
